@startuml
title "isInheritedFunction.kt Plantuml"

    '.<ERROR TYPE: KSFunctionDeclaration>
    class "<ERROR TYPE: KSFunctionDeclaration>" as <ERROR TYPE: KSFunctionDeclaration> {
        ...
==

		+ <ext> isInherited() : Boolean
    }


    '.<ERROR TYPE: KSPropertyDeclaration>
    class "<ERROR TYPE: KSPropertyDeclaration>" as <ERROR TYPE: KSPropertyDeclaration> {
        ...
==

		+ <ext> isInherited() : Boolean
    }



@enduml
