@startuml
title "02_server_config_default.kt Plantuml"

    '.Server
    interface "Server" as Server {
        + start() : Unit
		+ stop() : Unit
    }


    'Server.Config
    interface "Server.Config" as Server_Config {
        + {static} Default : Config
		+ ipAddress : String
		+ port : Int
    }



@enduml
