package docgeneration

import CompilationTest
import com.tschuchort.compiletesting.SourceFile
import com.tschuchort.compiletesting.sourcesGeneratedBySymbolProcessor
import ensureEndsWith
import org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi
import org.jetbrains.kotlin.incremental.createDirectory
import org.jetbrains.kotlin.ir.types.IdSignatureValues.result
import org.junit.jupiter.api.Test
import java.io.File

const val GENERATION_REFERENCE_COMMENT = "'This file is generated by the GenerateExamplesForDoc test."

class GenerationForDoc : CompilationTest() {

    val dataClassCode = """
    package my.pck
    data class Foo(val x: String, val y: String, val z : Int)
    """

    val interfaceCode = """
    package com.google.devtools.ksp.processing
    import com.google.devtools.ksp.symbol.KSAnnotated
    interface SymbolProcessor {
        fun process(resolver: Resolver): List<KSAnnotated>
        fun finish()
        fun onError()
    }
    """

    val extensionFunctionsCode = """
    package my.pck
    class Color(val hex:String) {
        companion object
    }
    
    fun Color.halfTransparent() : Color = Color("7f"+this.hex.takeLast(6))
    val Color.Companion.red : Color
        get() = Color("ffff0000")
    fun Color.Companion.byRGBInt(alpha : Int, red : Int, green : Int, blue : Int) : Color = Color(alpha.toString(16)+red.toString(16)+green.toString(16)+blue.toString(16))
    """

    val objectCode = """
    package my.logging
    object Logger {
        fun warn(message:String){}
        fun warn(message:()->String) = warn(message()) 
        fun info(message:String){}
        fun info(message:()->String) = info(message()) 
        fun verbose(message:String){}
        fun verbose(message:()->String) = verbose(message()) 
        fun error(message:String, throwable:Throwable?=null){}
        fun error(message:()->String, throwable:Throwable?=null) = error(message(),throwable)
    }
    """

    val companionObjectCode = """
    package user
    class User private constructor(val name: String) {
        // Defines a companion object that acts as a factory for creating User instances
        companion object Factory {
            fun create(name: String): User = User(name)
            fun createOnlyIfValid(name:String): User? = name.takeIf{ it.isNotEmpty() }?.let{ User(name) }
        }
    }  
    """

    val enumsCode = """
    package trafficLight
    enum class TrafficLights(val description:String) {
        RED("You better stay"),
        YELLOW("If you think about it, better stand still"),
        GREEN("Lets go!");
        fun canCrossSafely():Boolean = when(this){
            GREEN -> true
            RED, YELLOW -> false
        }
    }  
    """

    val inheritanceCode = """
    // Example inspired from https://en.wikipedia.org/wiki/Factory_method_pattern
    interface Room {
        fun connect(room: Room?)
    }
    
    class MagicRoom : Room {
        override fun connect(room: Room?) {}
    }
    
    class OrdinaryRoom : Room {
        override fun connect(room: Room?) {}
    }
    
    abstract class MazeGame {
        val rooms: MutableList<Room> = ArrayList()
    
        init {
            val room1 = makeRoom()
            val room2 = makeRoom()
            room1.connect(room2)
            rooms.add(room1)
            rooms.add(room2)
        }
    
        protected abstract fun makeRoom(): Room
    }
    class MagicMazeGame : MazeGame() {
        override fun makeRoom(): MagicRoom {
            return MagicRoom()
        }
    }
    
    class OrdinaryMazeGame : MazeGame() {
        override fun makeRoom(): OrdinaryRoom {
            return OrdinaryRoom()
        }
    }  
    """

    val suspendCode = """
    package events
    data class Event(val id:Int)
    interface EventsRepository {
        val events : List<Event>
        suspend fun fetchEvents() : Result<Unit>
    }
    """

    val sealedClassesCode = """
    package ui
    sealed class UIState {
        data object Loading : UIState()
        data class Success(val data: String) : UIState()
        data class Error(val exception: Exception) : UIState()
    }
    """

    val shellForExtensionCode = """
    package plantuml.utils
    import java.io.File
    
    data class PlantumlTemplate(val content: String)
    
    fun File.writePlantuml(plantumlTemplate: PlantumlTemplate): Unit {
        this.writeText("startuml\n" + plantumlTemplate.content + "\nenduml")
    }
    
    val File.isPlantumlDiagram: Boolean
        get() = this.isFile && this.exists() && listOf("startuml", "enduml").all { it in this.readText() }
    """

    val indirectRelationsCode = """
    package person
    class Age(val value: Int)
    class Name(val firstName: String, val secondName: String)
    interface Company {
        val name: String
    }
    
    class Job<T : Company>()
    class Date(val day: Int, val month: Int, val year: Int)
    class Person(val birthday: Date, val name: Name, val peopleIKnow: List<Name>, val job: Job<Company>) {
        fun computeAge(): Result<Age> {
            return Result.success(Age(2025 - birthday.year))
        }
    }
    """

    val manyRelationsCode = """
    package problem
    data class Error(val description : String)
    interface OperationA {
        fun run(): Error?
    }
    interface OperationB {
        fun run(): Error?
    }
    interface OperationC {
        fun run(): Error?
    }
    interface OperationD {
        fun run(): Error?
    }
    interface OperationE {
        fun run(): Error?
    }
    interface OperationF {
        fun run(): Error?
    }
    interface OperationG {
        fun run(): Error?
    }
    """

    @OptIn(ExperimentalCompilerApi::class)
    @Test
    fun `generate Docs`() {
        listOf(
            Triple("DataClass", dataClassCode, DEFAULT_OPTIONS),
            Triple("Interface", interfaceCode, DEFAULT_OPTIONS),
            Triple("Extensions", extensionFunctionsCode, DEFAULT_OPTIONS),
            Triple("ExtensionsOfExternalClasses", shellForExtensionCode, DEFAULT_OPTIONS),
            Triple("Objects", objectCode, DEFAULT_OPTIONS),
            Triple("CompanionObjects", companionObjectCode, DEFAULT_OPTIONS),
            Triple("Enums", enumsCode, DEFAULT_OPTIONS),
            Triple("Inheritance", inheritanceCode, DEFAULT_OPTIONS),
            Triple("InheritanceWithInheritedFields", inheritanceCode, DEFAULT_OPTIONS.copy(showInheritedFunctions = true, showInheritedProperties = true)),
            Triple("SuspendFunctions", suspendCode, DEFAULT_OPTIONS),
            Triple("SealedClasses", sealedClassesCode, DEFAULT_OPTIONS),
            Triple("IndirectRelations", indirectRelationsCode, DEFAULT_OPTIONS),
            Triple("ManyRelations", manyRelationsCode, DEFAULT_OPTIONS),
        ).forEach { (name, code, options) ->
            val note = buildString {
                appendLine("note as note_of_code")
                val nonDefaultOptions = options.asMap().filter { DEFAULT_OPTIONS.asMap()[it.key] != it.value }.entries
                if (nonDefaultOptions.isNotEmpty()) {
                    appendLine("Non default options:")
                    appendLine(nonDefaultOptions.joinToString("\n") { "${it.key} = ${it.value}" })
                    appendLine()
                }
                appendLine("Kotlin Code:")
                appendLine(code)
                appendLine("end note")
            }
            newCompilation(options.copy(title = "Example for $name", prefix = GENERATION_REFERENCE_COMMENT, postfix = note), listOf(SourceFile.kotlin("$name.kt", code))).let {
                val result = it.compile()
                saveUMLInDocs(result.sourcesGeneratedBySymbolProcessor.first(), name)
            }
        }

        val boxCode = """
            package basic
            data class Box(val id: Int)
        """.trimIndent()

        val chestAliasCode = """
            package basic
            typealias Chest = Box
        """.trimIndent()

        val cartonAliasCode = """
            package advanced
            import basic.Box
            typealias Carton = Box
            fun Carton.matchesID(id:Int): Boolean {
                return id == ${'$'}{this.id} 
            }
        """.trimIndent()

        // TypeAlias example
        val code = listOf(SourceFile.kotlin("Box.kt", boxCode), SourceFile.kotlin("Chest.kt", chestAliasCode), SourceFile.kotlin("Carton.kt", cartonAliasCode))
        val note = buildString {
            appendLine("note as note_of_code_box")
            appendLine("Kotlin Code: Box.kt")
            appendLine(boxCode)
            appendLine("end note")
            appendLine("note as note_of_code_chest")
            appendLine("Kotlin Code: Chest.kt")
            appendLine(chestAliasCode)
            appendLine("end note")
            appendLine("note as note_of_code_carton")
            appendLine("Kotlin Code: Carton.kt")
            appendLine(cartonAliasCode)
            appendLine("end note")
        }
        newCompilation(options = DEFAULT_OPTIONS.copy(title = "Example for TypeAlias", prefix = GENERATION_REFERENCE_COMMENT, postfix = note), sources = code).let {
            val result = it.compile()
            saveUMLInDocs(result.sourcesGeneratedBySymbolProcessor.first(), "Example_for_TypeAlias")
        }
    }

    @Test
    fun `generate Default Config file`() {
        val docsFolder = File("../doc/").apply { createDirectory() }
        File(docsFolder, "default.conf").apply {
            delete()
            createNewFile()
            val preamble = """
# Example config file for the Plant uml generator
# Packages and Names can be separated with ','
# Boolean settings can be set with 'true' and 'false'
""".trimIndent()
            appendText(preamble)
            appendText("\n")
            appendText(DEFAULT_OPTIONS.asMap().entries.joinToString("\n") { (key, value) -> "$key=$value" })
        }
    }


    @OptIn(ExperimentalCompilerApi::class)
    @Test
    fun generatePumlForPresentation() {
        val files = File("../presentation").walkTopDown().toList().filter { it.name.endsWith(".kt") }
        files.forEach { ktFile ->
            newCompilation(options = DEFAULT_OPTIONS.copy(title = "\"${ktFile.name} Plantuml\""), sources = listOf(SourceFile.kotlin("${ktFile.name}", ktFile.readText(Charsets.UTF_8)))).let {
                val result = it.compile()
                val copiedFile = File(ktFile.parentFile, ktFile.nameWithoutExtension.ensureEndsWith(".puml")).apply { createNewFile() }
                result.sourcesGeneratedBySymbolProcessor.first().copyTo(copiedFile, overwrite = true)
            }
        }
    }

}